// animals-data.js — Animal database for EchoedWild
// This file contains all animal data directly embedded to ensure reliable loading

console.log('Loading animals-data.js...');

const animalsData = [
  {
    name: "Giant Panda",
    status: "Vulnerable",
    region: "Asia",
    estimated: "~1,864",
    image: "images/giant-panda.png",
    link: "animals/giant-panda.html",
    habitat: "Bamboo forests in mountainous regions of central China",
    threats: ["Habitat loss", "Climate change", "Poaching"],
    conservation: ["Protected nature reserves", "Bamboo restoration projects", "Anti-poaching patrols"]
  },
  {
    name: "Sumatran Tiger",
    status: "Critically Endangered",
    region: "Asia",
    estimated: "~400",
    image: "images/sumatran-tiger.png",
    link: "animals/sumatran-tiger.html",
    habitat: "Tropical rainforests and peat swamp forests of Sumatra, Indonesia",
    threats: ["Habitat destruction", "Poaching for traditional medicine", "Human-wildlife conflict"],
    conservation: ["Anti-poaching units", "Habitat protection", "Community engagement programs"]
  },
  {
    name: "Black Rhino",
    status: "Critically Endangered",
    region: "Africa",
    estimated: "~5,500",
    image: "images/black-rhino.png",
    link: "animals/black-rhino.html",
    habitat: "Savannas, grasslands, and tropical bushlands in eastern and southern Africa",
    threats: ["Poaching for horns", "Habitat loss", "Political instability"],
    conservation: ["De-horning programs", "Strict anti-poaching laws", "Translocation to safe areas"]
  },
  {
    name: "African Elephant",
    status: "Vulnerable",
    region: "Africa",
    estimated: "~415,000",
    image: "images/african-elephant.png",
    link: "animals/african-elephant.html",
    habitat: "Savannas, forests, deserts, and marshes across sub-Saharan Africa",
    threats: ["Ivory poaching", "Habitat loss", "Human-wildlife conflict"],
    conservation: ["International ivory trade bans", "Protected area networks", "Elephant corridors"]
  },
  {
    name: "Vaquita",
    status: "Critically Endangered",
    region: "Americas",
    estimated: "<10",
    image: "images/vaquita.png",
    link: "animals/vaquita.html",
    habitat: "Northern Gulf of California, Mexico",
    threats: ["Bycatch in illegal gillnets", "Habitat degradation", "Limited range"],
    conservation: ["Gillnet bans", " captive breeding attempts", "International monitoring"]
  },
  {
    name: "Amur Leopard",
    status: "Critically Endangered",
    region: "Asia",
    estimated: "~100",
    image: "images/amur-leopard.png",
    link: "animals/amur-leopard.html",
    habitat: "Temperate forests in the Russian Far East and northeast China",
    threats: ["Habitat loss", "Poaching for skins", "Prey depletion"],
    conservation: ["Protected areas", "Anti-poaching patrols", "Prey population restoration"]
  },
  {
    name: "Koala",
    status: "Vulnerable",
    region: "Oceania",
    estimated: "~300,000",
    image: "images/koala.png",
    link: "animals/koala.html",
    habitat: "Eucalyptus forests and woodlands in eastern Australia",
    threats: ["Habitat loss", "Bushfires", "Climate change", "Disease"],
    conservation: ["Habitat protection", "Disease research", "Fire management programs"]
  },
  {
    name: "Mountain Gorilla",
    status: "Endangered",
    region: "Africa",
    estimated: "~1,063",
    image: "images/mountain-gorilla.png",
    link: "animals/mountain-gorilla.html",
    habitat: "Montane and bamboo forests in central Africa",
    threats: ["Habitat loss", "Poaching", "Disease", "Civil unrest"],
    conservation: ["Protected area management", "Community-based conservation", "Ecotourism"]
  },
  {
    name: "Great Hammerhead",
    status: "Endangered",
    region: "Global",
    estimated: "~50,000 – 70,000",
    image: "images/great-hammerhead.png",
    link: "animals/great-hammerhead.html",
    habitat: "Tropical and warm temperate oceans worldwide",
    threats: ["Overfishing", "Bycatch", "Shark fin trade", "Habitat degradation"],
    conservation: ["Fishing regulations", "Marine protected areas", "Shark fin trade bans"]
  },
  {
    name: "Snow Leopard",
    status: "Vulnerable",
    region: "Asia",
    estimated: "~4,000–6,500",
    image: "images/snow-leopard.png",
    link: "animals/snow-leopard.html",
    habitat: "High mountain ranges of Central and South Asia",
    threats: ["Poaching", "Habitat loss", "Human-wildlife conflict", "Climate change"],
    conservation: ["Protected areas", "Community conservation programs", "Anti-poaching efforts"]
  },
  {
    name: "Red Panda",
    status: "Endangered",
    region: "Asia",
    estimated: "~10,000",
    image: "images/red-panda.png",
    link: "animals/red-panda.html",
    habitat: "Temperate forests of the Himalayas and surrounding regions",
    threats: ["Habitat loss", "Poaching", "Fragmentation", "Climate change"],
    conservation: ["Protected areas", "Community-based conservation", "Reforestation"]
  },
  {
    name: "Saola",
    status: "Critically Endangered",
    region: "Asia",
    estimated: "<100",
    image: "images/saola.png",
    link: "animals/saola.html",
    habitat: "Evergreen forests in the Annamite Range of Vietnam and Laos",
    threats: ["Habitat loss", "Poaching", "Limited range"],
    conservation: ["Protected area establishment", "Anti-poaching patrols", "Community engagement"]
  },
  {
    name: "Northern Bald Ibis",
    status: "Endangered",
    region: "Europe, North Africa",
    estimated: "~1,000",
    image: "images/northern-bald-ibis.png",
    link: "animals/northern-bald-ibis.html",
    habitat: "Semi-arid steppes, rocky areas, and cliffs",
    threats: ["Habitat loss", "Hunting", "Disturbance", "Pesticide use"],
    conservation: ["Breeding programs", "Protected areas", "Reintroduction efforts"]
  },
  {
    name: "Philippine Eagle",
    status: "Critically Endangered",
    region: "Asia",
    estimated: "~400",
    image: "images/philippine-eagle.png",
    link: "animals/philippine-eagle.html",
    habitat: "Tropical rainforests in the Philippines",
    threats: ["Habitat loss", "Poaching", "Human encroachment"],
    conservation: ["Protected area management", "Breeding programs", "Community education"]
  },
  {
    name: "Axolotl",
    status: "Critically Endangered",
    region: "Americas",
    estimated: "Unknown (wild population extremely low)",
    image: "images/axolotl.png",
    link: "animals/axolotl.html",
    habitat: "Lake Xochimilco and surrounding canals in Mexico City",
    threats: ["Habitat loss", "Water pollution", "Invasive species", "Urbanization"],
    conservation: ["Habitat restoration", "Captive breeding", "Water quality improvement"]
  },
  {
    name: "Blue Whale",
    status: "Endangered",
    region: "Global",
    estimated: "10,000–25,000 individuals",
    image: "images/blue-whale.png",
    link: "animals/blue-whale.html",
    habitat: "All oceans worldwide, prefer deep waters",
    threats: ["Ship strikes", "Entanglement in fishing gear", "Ocean noise", "Climate change"],
    conservation: ["Ship speed limits", "Fishing gear modifications", "Marine protected areas"]
  },
  {
    name: "Asian Giant Hornet",
    status: "Near Threatened",
    region: "East Asia",
    estimated: "Unknown",
    image: "images/asian-giant-hornet.png",
    link: "animals/asian-giant-hornet.html",
    habitat: "Forests and rural areas in East Asia",
    threats: ["Habitat loss", "Pesticide use", "Collection for traditional medicine"],
    conservation: ["Habitat protection", "Monitoring programs", "Public education"]
  },
  {
    name: "Ball Python",
    status: "Near Threatened",
    region: "West and Central Africa",
    estimated: "Stable but declining",
    image: "images/ball-python.png",
    link: "animals/ball-python.html",
    habitat: "Savannas and grasslands in sub-Saharan Africa",
    threats: ["Pet trade", "Habitat loss", "Human persecution"],
    conservation: ["Trade regulations", "Habitat protection", "Sustainable use programs"]
  },
  {
    name: "Red Wolf",
    status: "Critically Endangered",
    region: "North Carolina",
    estimated: "28-31",
    image: "images/red-wolf.png",
    link: "animals/red-wolf.html",
    habitat: "Forests, swamps, and coastal prairies in the southeastern US",
    threats: ["Habitat loss", "Hybridization with coyotes", "Human persecution", "Vehicle collisions"],
    conservation: ["Captive breeding", "Reintroduction programs", "Protected areas"]
  },
  {
    name: "Sea Otter",
    status: "Threatened",
    region: "North Pacific Coast",
    estimated: "~3,000 (Southern population)",
    image: "images/sea-otter.png",
    link: "animals/sea-otter.html",
    habitat: "Coastal waters of the northern Pacific Ocean",
    threats: ["Oil spills", "Entanglement in fishing gear", "Predation", "Disease"],
    conservation: ["Oil spill response", "Fishing regulations", "Protected areas"]
  },
  {
    name: "Addax",
    status: "Critically Endangered",
    region: "Sahara Desert (Niger, Chad, Morocco)",
    estimated: "<100 in the wild",
    image: "images/addax.png",
    link: "animals/addax.html",
    habitat: "Sandy desert areas in the Sahara",
    threats: ["Poaching", "Habitat loss", "Climate change", "Civil unrest"],
    conservation: ["Protected areas", "Captive breeding", "Anti-poaching efforts"]
  },
  {
    name: "Pangolin",
    status: "Critically Endangered",
    region: "Asia & Africa (Forests, Grasslands, Savannas)",
    estimated: "Unknown (all 8 species declining)",
    image: "images/pangolin.png",
    link: "animals/pangolin.html",
    habitat: "Various habitats across Asia and Africa",
    threats: ["Poaching for scales and meat", "Habitat loss", "Illegal wildlife trade"],
    conservation: ["Trade bans", "Protected areas", "Anti-poaching efforts", "Public awareness"]
  },
  {
    name: "Lemur",
    status: "Critically Endangered",
    region: "Madagascar (Rainforests, Spiny Forests, Dry Forests)",
    estimated: "98% of species endangered",
    image: "images/lemur.png",
    link: "animals/lemur.html",
    habitat: "Various forest types across Madagascar",
    threats: ["Habitat loss", "Hunting", "Climate change", "Invasive species"],
    conservation: ["Protected areas", "Community conservation", "Reforestation"]
  },
  {
    name: "Orangutan",
    status: "Critically Endangered",
    region: "Borneo & Sumatra (Tropical Rainforests)",
    estimated: "~50,000 (all species combined)",
    image: "images/orangutan.png",
    link: "animals/orangutan.html",
    habitat: "Tropical rainforests of Borneo and Sumatra",
    threats: ["Habitat loss for palm oil", "Poaching", "Pet trade", "Climate change"],
    conservation: ["Protected areas", "Sustainable palm oil", "Anti-poaching", "Rehabilitation"]
  },
  {
    name: "Tiger",
    status: "Endangered",
    region: "Asia (India, Russia, Indonesia, Nepal, Bhutan)",
    estimated: "~5,574 wild tigers",
    image: "images/tiger.png",
    link: "animals/tiger.html",
    habitat: "Various habitats across Asia from rainforests to grasslands",
    threats: ["Poaching for body parts", "Habitat loss", "Human-wildlife conflict", "Prey depletion"],
    conservation: ["Protected areas", "Anti-poaching", "Prey restoration", "Community engagement"]
  },
  {
    name: "Rhinoceros",
    status: "Critically Endangered",
    region: "Africa & Asia (Savannas, Forests, Wetlands)",
    estimated: "<28,000 across all 5 species",
    image: "images/rhinoceros.png",
    link: "animals/rhinoceros.html",
    habitat: "Various habitats across Africa and Asia",
    threats: ["Poaching for horns", "Habitat loss", "Political instability"],
    conservation: ["Anti-poaching", "De-horning", "Protected areas", "Trade bans"]
  },
  {
    name: "Kakapo",
    status: "Critically Endangered",
    region: "New Zealand (Codfish Island, Anchor Island, Little Barrier Island)",
    estimated: "238 individuals",
    image: "images/kakapo.png",
    link: "animals/kakapo.html",
    habitat: "Offshore islands of New Zealand",
    threats: ["Predation by introduced species", "Habitat loss", "Limited genetic diversity"],
    conservation: ["Predator-free islands", "Captive breeding", "Intensive monitoring"]
  },
  {
    name: "African Wild Dog",
    status: "Endangered",
    region: "Sub-Saharan Africa (Savannas, Woodlands, Plains)",
    estimated: "~6,600 individuals",
    image: "images/african-wild-dog.png",
    link: "animals/african-wild-dog.html",
    habitat: "Savannas, woodlands, and plains across sub-Saharan Africa",
    threats: ["Habitat loss", "Human-wildlife conflict", "Disease", "Persecution"],
    conservation: ["Protected areas", "Community engagement", "Disease management"]
  },
  {
    name: "Chimpanzee",
    status: "Endangered",
    region: "Central & West Africa (Rainforests, Savannas, Woodlands)",
    estimated: "172,700–299,700",
    image: "images/chimpanzee.png",
    link: "animals/chimpanzee.html",
    habitat: "Rainforests, savannas, and woodlands across central and west Africa",
    threats: ["Habitat loss", "Bushmeat hunting", "Disease", "Pet trade"],
    conservation: ["Protected areas", "Anti-poaching", "Community conservation", "Research"]
  },
  {
    name: "Aye-Aye",
    status: "Endangered",
    region: "Madagascar (Rainforests, Deciduous Forests, Plantations)",
    estimated: "Unknown",
    image: "images/aye-aye.png",
    link: "animals/aye-aye.html",
    habitat: "Rainforests and deciduous forests of Madagascar",
    threats: ["Habitat loss", "Persecution due to superstitions", "Hunting"],
    conservation: ["Protected areas", "Community education", "Habitat protection"]
  },
  {
    name: "Hawksbill Turtle",
    status: "Critically Endangered",
    region: "Global (Tropical Oceans)",
    estimated: "Unknown",
    image: "images/hawksbill-turtle.png",
    link: "animals/hawksbill-turtle.html",
    habitat: "Tropical coral reefs worldwide",
    threats: ["Poaching for shells", "Habitat loss", "Climate change", "Pollution"],
    conservation: ["Protected areas", "Trade bans", "Habitat restoration", "Public education"]
  },
  {
    name: "Iberian Lynx",
    status: "Endangered",
    region: "Europe (Spain, Portugal)",
    estimated: "~1,000",
    image: "images/iberian-lynx.png",
    link: "animals/iberian-lynx.html",
    habitat: "Mediterranean forests and scrubland in Spain and Portugal",
    threats: ["Habitat loss", "Prey depletion", "Road accidents", "Disease"],
    conservation: ["Reintroduction programs", "Habitat restoration", "Prey population recovery"]
  },
  {
    name: "Javan Rhino",
    status: "Critically Endangered",
    region: "Asia (Indonesia)",
    estimated: "~75",
    image: "images/javan-rhino.png",
    link: "animals/javan-rhino.html",
    habitat: "Tropical rainforests in Ujung Kulon National Park, Indonesia",
    threats: ["Habitat loss", "Poaching", "Natural disasters", "Disease"],
    conservation: ["Protected area management", "Anti-poaching", "Population monitoring"]
  },
  {
    name: "Greater One-Horned Rhino",
    status: "Vulnerable",
    region: "Asia (India, Nepal)",
    estimated: "~4,000",
    image: "images/greater-one-horned-rhino.png",
    link: "animals/greater-one-horned-rhino.html",
    habitat: "Grasslands and forests in India and Nepal",
    threats: ["Poaching for horns", "Habitat loss", "Human-wildlife conflict"],
    conservation: ["Protected areas", "Anti-poaching", "Community conservation"]
  },
  {
    name: "Dhole",
    status: "Endangered",
    region: "Asia",
    estimated: "~2,500",
    image: "images/dhole.png",
    link: "animals/dhole.html",
    habitat: "Forests and grasslands across South and Southeast Asia",
    threats: ["Habitat loss", "Prey depletion", "Disease", "Persecution"],
    conservation: ["Protected areas", "Prey restoration", "Community engagement"]
  },
  {
    name: "African Penguin",
    status: "Endangered",
    region: "Africa (Southern coast)",
    estimated: "~50,000",
    image: "images/african-penguin.png",
    link: "animals/african-penguin.html",
    habitat: "Coastal areas and islands of southern Africa",
    threats: ["Overfishing", "Oil spills", "Habitat disturbance", "Climate change"],
    conservation: ["Protected breeding sites", "Fishing regulations", "Rehabilitation centers"]
  },
  {
    name: "Scimitar-Horned Oryx",
    status: "Extinct in the Wild",
    region: "North Africa (Sahara)",
    estimated: "0 (captive population exists)",
    image: "images/scimitar-horned-oryx.png",
    link: "animals/scimitar-horned-oryx.html",
    habitat: "Semi-desert and desert areas of North Africa",
    threats: ["Hunting", "Habitat loss", "Competition with livestock"],
    conservation: ["Reintroduction programs", "Captive breeding", "Protected areas"]
  },
  {
    name: "Hirola",
    status: "Critically Endangered",
    region: "Africa (Kenya, Somalia)",
    estimated: "~500",
    image: "images/hirola.png",
    link: "animals/hirola.html",
    habitat: "Arid grasslands and shrublands on the Kenya-Somalia border",
    threats: ["Habitat loss", "Drought", "Poaching", "Disease"],
    conservation: ["Protected areas", "Community conservation", "Habitat restoration"]
  },
  {
    name: "Pygmy Hippopotamus",
    status: "Endangered",
    region: "Africa (West Africa)",
    estimated: "~2,000-2,500",
    image: "images/pygmy-hippopotamus.png",
    link: "animals/pygmy-hippopotamus.html",
    habitat: "Forests and swamps in West Africa",
    threats: ["Habitat loss", "Hunting", "Political instability"],
    conservation: ["Protected areas", "Community conservation", "Anti-poaching"]
  },
  {
    name: "Cross River Gorilla",
    status: "Critically Endangered",
    region: "Africa (Nigeria, Cameroon)",
    estimated: "~300",
    image: "images/cross-river-gorilla.png",
    link: "animals/cross-river-gorilla.html",
    habitat: "Montane forests on the Nigeria-Cameroon border",
    threats: ["Habitat loss", "Hunting", "Human encroachment"],
    conservation: ["Protected areas", "Community conservation", "Anti-poaching"]
  },
  {
    name: "Bactrian Camel",
    status: "Critically Endangered",
    region: "Asia (Mongolia, China)",
    estimated: "~1,400",
    image: "images/bactrian-camel.png",
    link: "animals/bactrian-camel.html",
    habitat: "Deserts and steppes of Mongolia and China",
    threats: ["Habitat loss", "Hunting", "Competition with livestock", "Climate change"],
    conservation: ["Protected areas", "Captive breeding", "Community engagement"]
  },
  {
    name: "Andean Mountain Cat",
    status: "Endangered",
    region: "South America (Andes)",
    estimated: "~1,400",
    image: "images/andean-mountain-cat.png",
    link: "animals/andean-mountain-cat.html",
    habitat: "High altitude grasslands and rocky areas in the Andes",
    threats: ["Habitat loss", "Hunting", "Prey depletion"],
    conservation: ["Protected areas", "Research and monitoring", "Community education"]
  },
  {
    name: "Arabian Oryx",
    status: "Vulnerable",
    region: "Middle East (Arabian Peninsula)",
    estimated: "~1,200",
    image: "images/arabian-oryx.png",
    link: "animals/arabian-oryx.html",
    habitat: "Desert and steppe areas of the Arabian Peninsula",
    threats: ["Habitat loss", "Climate change", "Competition with livestock"],
    conservation: ["Protected areas", "Reintroduction programs", "Community conservation"]
  },
  {
    name: "Arctic Wolf",
    status: "Least Concern",
    region: "Arctic (North America, Greenland)",
    estimated: "~200,000",
    image: "images/arctic-wolf.png",
    link: "animals/arctic-wolf.html",
    habitat: "Arctic tundra and ice fields",
    threats: ["Climate change", "Habitat loss", "Human disturbance"],
    conservation: ["Protected areas", "Climate action", "Sustainable development"]
  },
  {
    name: "Asian Elephant",
    status: "Endangered",
    region: "Asia (Southeast Asia, India)",
    estimated: "~50,000",
    image: "images/asian-elephant.png",
    link: "animals/asian-elephant.html",
    habitat: "Forests and grasslands across Asia",
    threats: ["Habitat loss", "Human-wildlife conflict", "Poaching"],
    conservation: ["Protected areas", "Elephant corridors", "Human-elephant conflict mitigation"]
  },
  {
    name: "Asiatic Lion",
    status: "Endangered",
    region: "Asia (India)",
    estimated: "~670",
    image: "images/asiatic-lion.png",
    link: "animals/asiatic-lion.html",
    habitat: "Gir Forest in Gujarat, India",
    threats: ["Habitat loss", "Human-wildlife conflict", "Disease", "Limited range"],
    conservation: ["Protected areas", "Habitat expansion", "Community conservation"]
  },
  {
    name: "Bay Cat",
    status: "Endangered",
    region: "Asia (Borneo)",
    estimated: "~2,500",
    image: "images/bay-cat.png",
    link: "animals/bay-cat.html",
    habitat: "Tropical rainforests of Borneo",
    threats: ["Habitat loss", "Deforestation"],
    conservation: ["Protected areas", "Habitat protection", "Research"]
  },
  {
    name: "Black-Backed Jackal",
    status: "Least Concern",
    region: "Africa",
    estimated: "Stable",
    image: "images/black-backed-jackal.png",
    link: "animals/black-backed-jackal.html",
    habitat: "Various habitats across Africa",
    threats: ["Persecution", "Habitat loss", "Disease"],
    conservation: ["Protected areas", "Sustainable management"]
  },
  {
    name: "Black-Footed Cat",
    status: "Vulnerable",
    region: "Africa (Southern Africa)",
    estimated: "~10,000",
    image: "images/black-footed-cat.png",
    link: "animals/black-footed-cat.html",
    habitat: "Arid regions of southern Africa",
    threats: ["Habitat loss", "Predator control", "Climate change"],
    conservation: ["Protected areas", "Research", "Community education"]
  },
  {
    name: "Bobcat",
    status: "Least Concern",
    region: "North America",
    estimated: "~3.5 million",
    image: "images/bobcat.png",
    link: "animals/bobcat.html",
    habitat: "Various habitats across North America",
    threats: ["Habitat loss", "Hunting", "Vehicle collisions"],
    conservation: ["Sustainable management", "Protected areas"]
  },
  {
    name: "Bornean Elephant",
    status: "Endangered",
    region: "Asia (Borneo)",
    estimated: "~1,500",
    image: "images/bornean-elephant.png",
    link: "animals/bornean-elephant.html",
    habitat: "Tropical rainforests of Borneo",
    threats: ["Habitat loss for palm oil", "Human-wildlife conflict", "Poaching"],
    conservation: ["Protected areas", "Habitat corridors", "Community conservation"]
  },
  {
    name: "Brown Hyena",
    status: "Near Threatened",
    region: "Africa (Southern Africa)",
    estimated: "~5,000-8,000",
    image: "images/brown-hyena.png",
    link: "animals/brown-hyena.html",
    habitat: "Arid and semi-arid regions of southern Africa",
    threats: ["Persecution", "Habitat loss", "Declining prey"],
    conservation: ["Protected areas", "Community education", "Research"]
  },
  {
    name: "Canadian Lynx",
    status: "Least Concern",
    region: "North America (Canada, Alaska)",
    estimated: "~100,000",
    image: "images/canadian-lynx.png",
    link: "animals/canadian-lynx.html",
    habitat: "Boreal forests of Canada and Alaska",
    threats: ["Habitat loss", "Climate change", "Hunting"],
    conservation: ["Protected areas", "Sustainable management", "Climate action"]
  },
  {
    name: "Caracal",
    status: "Least Concern",
    region: "Africa, Asia, Middle East",
    estimated: "Stable",
    image: "images/caracal.png",
    link: "animals/caracal.html",
    habitat: "Various habitats across Africa, Asia, and the Middle East",
    threats: ["Habitat loss", "Persecution", "Hunting"],
    conservation: ["Protected areas", "Sustainable management"]
  },
  {
    name: "Cheetah",
    status: "Vulnerable",
    region: "Africa, Iran",
    estimated: "~7,100",
    image: "images/cheetah.png",
    link: "animals/cheetah.html",
    habitat: "Savannas and grasslands of Africa and Iran",
    threats: ["Habitat loss", "Human-wildlife conflict", "Poaching", "Climate change"],
    conservation: ["Protected areas", "Community conservation", "Anti-poaching"]
  },
  {
    name: "Clouded Leopard",
    status: "Vulnerable",
    region: "Asia (Southeast Asia, Himalayas)",
    estimated: "~10,000",
    image: "images/clouded-leopard.png",
    link: "animals/clouded-leopard.html",
    habitat: "Tropical and subtropical forests of Southeast Asia",
    threats: ["Habitat loss", "Poaching", "Climate change"],
    conservation: ["Protected areas", "Anti-poaching", "Habitat protection"]
  },
  {
    name: "Cougar",
    status: "Least Concern",
    region: "Americas",
    estimated: "~30,000",
    image: "images/cougar.png",
    link: "animals/cougar.html",
    habitat: "Various habitats across the Americas",
    threats: ["Habitat loss", "Human-wildlife conflict", "Hunting"],
    conservation: ["Sustainable management", "Protected areas"]
  },
  {
    name: "Coyote",
    status: "Least Concern",
    region: "North America",
    estimated: "~1-2 million",
    image: "images/coyote.png",
    link: "animals/coyote.html",
    habitat: "Various habitats across North America",
    threats: ["Persecution", "Habitat loss", "Disease"],
    conservation: ["Sustainable management", "Public education"]
  },
  {
    name: "Dama Gazelle",
    status: "Critically Endangered",
    region: "Africa (Sahara)",
    estimated: "~400",
    image: "images/dama-gazelle.png",
    link: "animals/dama-gazelle.html",
    habitat: "Desert and semi-desert areas of the Sahara",
    threats: ["Hunting", "Habitat loss", "Climate change"],
    conservation: ["Protected areas", "Captive breeding", "Anti-poaching"]
  },
  {
    name: "Ethiopian Wolf",
    status: "Endangered",
    region: "Africa (Ethiopia)",
    estimated: "~500",
    image: "images/ethiopian-wolf.png",
    link: "animals/ethiopian-wolf.html",
    habitat: "Alpine grasslands of Ethiopia",
    threats: ["Habitat loss", "Disease", "Human encroachment"],
    conservation: ["Protected areas", "Vaccination programs", "Community conservation"]
  },
  {
    name: "Eurasian Lynx",
    status: "Least Concern",
    region: "Europe, Asia",
    estimated: "~50,000",
    image: "images/eurasian-lynx.png",
    link: "animals/eurasian-lynx.html",
    habitat: "Forests across Europe and Asia",
    threats: ["Habitat loss", "Hunting", "Vehicle collisions"],
    conservation: ["Protected areas", "Reintroduction programs", "Sustainable management"]
  },
  {
    name: "Fishing Cat",
    status: "Vulnerable",
    region: "Asia (South, Southeast Asia)",
    estimated: "~10,000",
    image: "images/fishing-cat.png",
    link: "animals/fishing-cat.html",
    habitat: "Wetlands and mangrove forests of South and Southeast Asia",
    threats: ["Habitat loss", "Hunting", "Pollution"],
    conservation: ["Protected areas", "Wetland conservation", "Community education"]
  },
  {
    name: "Flat-Headed Cat",
    status: "Endangered",
    region: "Asia (Southeast Asia)",
    estimated: "~2,500",
    image: "images/flat-headed-cat.png",
    link: "animals/flat-headed-cat.html",
    habitat: "Tropical rainforests and wetlands of Southeast Asia",
    threats: ["Habitat loss", "Pollution", "Hunting"],
    conservation: ["Protected areas", "Wetland conservation", "Research"]
  },
{
    name: "Giant Sable Antelope",
    status: "Critically Endangered",
    region: "Africa (Angola)",
    estimated: "~200",
    image: "images/giant-sable-antelope.png",
    link: "animals/giant-sable-antelope.html",
    habitat: "Miombo woodlands of Angola",
    threats: ["Civil war", "Hunting", "Habitat loss"],
    conservation: ["Protected areas", "Anti-poaching", "Community conservation"]
  },
{
    name: "Golden Jackal",
    status: "Least Concern",
    region: "Europe, Asia, Africa",
    estimated: "Stable",
    image: "images/golden-jackal.png",
    link: "animals/golden-jackal.html",
    habitat: "Various habitats across Europe, Asia, and Africa",
    threats: ["Persecution", "Habitat loss", "Disease"],
    conservation: ["Sustainable management", "Protected areas"]
  },
  {
    name: "Grey Wolf",
    status: "Least Concern",
    region: "North America, Europe, Asia",
    estimated: "~200,000",
    image: "images/grey-wolf.png",
    link: "animals/grey-wolf.html",
    habitat: "Various habitats across the Northern Hemisphere",
    threats: ["Habitat loss", "Persecution", "Human-wildlife conflict"],
    conservation: ["Protected areas", "Reintroduction programs", "Sustainable management"]
  },
  {
    name: "Jaguar",
    status: "Near Threatened",
    region: "Americas",
    estimated: "~173,000",
    image: "images/jaguar.png",
    link: "animals/jaguar.html",
    habitat: "Rainforests, wetlands, and grasslands of the Americas",
    threats: ["Habitat loss", "Hunting", "Human-wildlife conflict"],
    conservation: ["Protected areas", "Habitat corridors", "Community conservation"]
  },
  {
    name: "Leopard",
    status: "Vulnerable",
    region: "Africa, Asia",
    estimated: "~50,000",
    image: "images/leopard.png",
    link: "animals/leopard.html",
    habitat: "Various habitats across Africa and Asia",
    threats: ["Habitat loss", "Hunting", "Human-wildlife conflict"],
    conservation: ["Protected areas", "Anti-poaching", "Community conservation"]
  },
  {
    name: "Long-Eared Jerboa",
    status: "Least Concern",
    region: "Asia (Mongolia, China)",
    estimated: "Unknown",
    image: "images/long-eared-jerboa.png",
    link: "animals/long-eared-jerboa.html",
    habitat: "Deserts of Mongolia and China",
    threats: ["Habitat degradation", "Climate change"],
    conservation: ["Habitat protection", "Research"]
  },
  {
    name: "Maned Wolf",
    status: "Near Threatened",
    region: "South America",
    estimated: "~23,000",
    image: "images/maned-wolf.png",
    link: "animals/maned-wolf.html",
    habitat: "Grasslands and savannas of South America",
    threats: ["Habitat loss", "Hunting", "Vehicle collisions"],
    conservation: ["Protected areas", "Habitat restoration", "Community education"]
  },
  {
    name: "Marbled Cat",
    status: "Near Threatened",
    region: "Asia (Southeast Asia)",
    estimated: "~10,000",
    image: "images/marbled-cat.png",
    link: "animals/marbled-cat.html",
    habitat: "Tropical forests of Southeast Asia",
    threats: ["Habitat loss", "Hunting"],
    conservation: ["Protected areas", "Habitat protection", "Research"]
  },
  {
    name: "Margay",
    status: "Near Threatened",
    region: "Americas (Central, South America)",
    estimated: "~10,000",
    image: "images/margay.png",
    link: "animals/margay.html",
    habitat: "Tropical forests of Central and South America",
    threats: ["Habitat loss", "Hunting", "Pet trade"],
    conservation: ["Protected areas", "Trade regulations", "Habitat protection"]
  },
  {
    name: "Mexican Wolf",
    status: "Endangered",
    region: "North America (Mexico, US)",
    estimated: "~180",
    image: "images/mexican-wolf.png",
    link: "animals/mexican-wolf.html",
    habitat: "Forests and grasslands of Mexico and southwestern US",
    threats: ["Habitat loss", "Human-wildlife conflict", "Genetic diversity"],
    conservation: ["Reintroduction programs", "Protected areas", "Captive breeding"]
  },
  {
    name: "Mountain Bongo",
    status: "Critically Endangered",
    region: "Africa (Kenya)",
    estimated: "~100",
    image: "images/mountain-bongo.png",
    link: "animals/mountain-bongo.html",
    habitat: "Forests of Kenya",
    threats: ["Hunting", "Habitat loss", "Disease"],
    conservation: ["Protected areas", "Captive breeding", "Anti-poaching"]
  },
  {
    name: "Ocelot",
    status: "Least Concern",
    region: "Americas",
    estimated: "~1-2 million",
    image: "images/ocelot.png",
    link: "animals/ocelot.html",
    habitat: "Various habitats across the Americas",
    threats: ["Habitat loss", "Hunting", "Pet trade"],
    conservation: ["Protected areas", "Trade regulations", "Sustainable management"]
  },
  {
    name: "Pallas's Cat",
    status: "Near Threatened",
    region: "Asia (Central Asia)",
    estimated: "~15,000",
    image: "images/pallas-cat.png",
    link: "animals/pallas-cat.html",
    habitat: "Grasslands and steppes of Central Asia",
    threats: ["Habitat loss", "Hunting", "Prey depletion"],
    conservation: ["Protected areas", "Research", "Community education"]
  },
  {
    name: "Pampas Cat",
    status: "Near Threatened",
    region: "South America",
    estimated: "~10,000",
    image: "images/pampas-cat.png",
    link: "animals/pampas-cat.html",
    habitat: "Grasslands and forests of South America",
    threats: ["Habitat loss", "Hunting", "Road mortality"],
    conservation: ["Protected areas", "Research", "Community education"]
  },
  {
    name: "Rusty-Spotted Cat",
    status: "Near Threatened",
    region: "Asia (India, Sri Lanka, Nepal)",
    estimated: "~10,000",
    image: "images/rusty-spotted-cat.png",
    link: "animals/rusty-spotted-cat.html",
    habitat: "Forests and grasslands of South Asia",
    threats: ["Habitat loss", "Hunting"],
    conservation: ["Protected areas", "Habitat protection", "Research"]
  },
  {
    name: "Sand Cat",
    status: "Least Concern",
    region: "Africa, Asia (Deserts)",
    estimated: "Unknown",
    image: "images/sand-cat.png",
    link: "animals/sand-cat.html",
    habitat: "Deserts of North Africa, Arabia, and Central Asia",
    threats: ["Habitat degradation", "Hunting", "Climate change"],
    conservation: ["Protected areas", "Research", "Habitat protection"]
  },
  {
    name: "Serval",
    status: "Least Concern",
    region: "Africa (Sub-Saharan)",
    estimated: "~50,000",
    image: "images/serval.png",
    link: "animals/serval.html",
    habitat: "Savannas and wetlands of sub-Saharan Africa",
    threats: ["Habitat loss", "Hunting", "Pet trade"],
    conservation: ["Protected areas", "Trade regulations", "Sustainable management"]
  },
  {
    name: "Side-Striped Jackal",
    status: "Least Concern",
    region: "Africa (Sub-Saharan)",
    estimated: "Stable",
    image: "images/side-striped-jackal.png",
    link: "animals/side-striped-jackal.html",
    habitat: "Various habitats across sub-Saharan Africa",
    threats: ["Habitat loss", "Persecution", "Disease"],
    conservation: ["Protected areas", "Sustainable management"]
  }
];

// Make the data available globally
window.animalsData = animalsData;

console.log(`animals-data.js loaded with ${animalsData.length} animals`);